export const ARTISTS_FETCH_STARTED = 'ARTISTS_FETCH_STARTED';
export const ARTISTS_FETCH_COMPLETED = 'ARTISTS_FETCH_COMPLETED';
export const ARTISTS_FETCH_FAILED = 'ARTISTS_FETCH_FAILED';

export const ARTIST_FETCH_STARTED = 'ARTIST_FETCH_STARTED';
export const ARTIST_FETCH_COMPLETED = 'ARTIST_FETCH_COMPLETED';
export const ARTIST_FETCH_FAILED = 'ARTIST_FETCH_FAILED';

export const ARTIST_ADD_STARTED = 'ARTIST_ADD_STARTED';
export const ARTIST_ADD_COMPLETED = 'ARTIST_ADD_COMPLETED';
export const ARTIST_ADD_FAILED = 'ARTIST_ADD_FAILED';

export const ARTIST_UPDATE_STARTED = 'ARTIST_UPDATE_STARTED';
export const ARTIST_UPDATE_COMPLETED = 'ARTIST_UPDATE_COMPLETED';
export const ARTIST_UPDATE_FAILED = 'ARTIST_UPDATE_FAILED';

export const ARTIST_REMOVE_STARTED = 'ARTIST_REMOVE_STARTED';
export const ARTIST_REMOVE_COMPLETED = 'ARTIST_REMOVE_COMPLETED';
export const ARTIST_REMOVE_FAILED = 'ARTIST_REMOVE_FAILED';
