export const SIGNIN_USER_STARTED = 'SIGNIN_USER_STARTED';
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED';
export const SIGNIN_USER_COMPLETED = 'SIGNIN_USER_SUCCESS';

export const SIGNUP_USER_STARTED = 'SIGNIN_USER_STARTED';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const SIGNUP_USER_COMPLETED = 'SIGNUP_USER_SUCCESS';

export const SIGNOUT_USER_COMPLETED = 'SIGNOUT_USER_SUCCESS';
