export const TRACK_ADDED_TO_CART = 'TRACK_ADDED_TO_CART';
export const TRACK_REMOVED_FROM_CART = 'TRACK_REMOVED_FROM_CART';
export const TRACK_QUANTITY_MODIFIED = 'TRACK_QUANTITY_MODIFIED';
export const CHECKOUT_STARTED = 'CHECKOUT_STARTED';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';
export const CHECKOUT_COMPLETED = 'CHECKOUT_COMPLETED';

export const UPLOAD_INVOICELINE_STARTED = 'UPLOAD_INVOICELINE_STARTED';
export const UPLOAD_INVOICELINE_FAILED = 'UPLOAD_INVOICELINE_FAILED';
export const UPLOAD_INVOICELINE_COMPLETED = 'UPLOAD_INVOICELINE_COMPLETED';

