export const TRACKS_FETCH_STARTED = 'TRACKS_FETCH_STARTED';
export const TRACKS_FETCH_COMPLETED = 'TRACKS_FETCH_COMPLETED';
export const TRACKS_FETCH_FAILED = 'TRACKS_FETCH_FAILED';

export const TRACK_FETCH_STARTED = 'TRACK_FETCH_STARTED';
export const TRACK_FETCH_COMPLETED = 'TRACK_FETCH_COMPLETED';
export const TRACK_FETCH_FAILED = 'TRACK_FETCH_FAILED';

export const TRACK_ADD_STARTED = 'TRACK_ADD_STARTED';
export const TRACK_ADD_COMPLETED = 'TRACK_ADD_COMPLETED';
export const TRACK_ADD_FAILED = 'TRACK_ADD_FAILED';

export const TRACK_UPDATE_STARTED = 'TRACK_UPDATE_STARTED';
export const TRACK_UPDATE_COMPLETED = 'TRACK_UPDATE_COMPLETED';
export const TRACK_UPDATE_FAILED = 'TRACK_UPDATE_FAILED';

export const TRACK_REMOVE_STARTED = 'TRACK_REMOVE_STARTED';
export const TRACK_REMOVE_COMPLETED = 'TRACK_REMOVE_COMPLETED';
export const TRACK_REMOVE_FAILED = 'TRACK_REMOVE_FAILED';
