export const ALBUMS_FETCH_STARTED = 'ALBUMS_FETCH_STARTED';
export const ALBUMS_FETCH_COMPLETED = 'ALBUMS_FETCH_COMPLETED';
export const ALBUMS_FETCH_FAILED = 'ALBUMS_FETCH_FAILED';

export const ALBUM_FETCH_STARTED = 'ALBUM_FETCH_STARTED';
export const ALBUM_FETCH_COMPLETED = 'ALBUM_FETCH_COMPLETED';
export const ALBUM_FETCH_FAILED = 'ALBUM_FETCH_FAILED';

export const ALBUM_ADD_STARTED = 'ALBUM_ADD_STARTED';
export const ALBUM_ADD_COMPLETED = 'ALBUM_ADD_COMPLETED';
export const ALBUM_ADD_FAILED = 'ALBUM_ADD_FAILED';

export const ALBUM_UPDATE_STARTED = 'ALBUM_UPDATE_STARTED';
export const ALBUM_UPDATE_COMPLETED = 'ALBUM_UPDATE_COMPLETED';
export const ALBUM_UPDATE_FAILED = 'ALBUM_UPDATE_FAILED';

export const ALBUM_REMOVE_STARTED = 'ALBUM_REMOVE_STARTED';
export const ALBUM_REMOVE_COMPLETED = 'ALBUM_REMOVE_COMPLETED';
export const ALBUM_REMOVE_FAILED = 'ALBUM_REMOVE_FAILED';
