export const USERS_FETCH_STARTED = 'USERS_FETCH_STARTED';
export const USERS_FETCH_COMPLETED = 'USERS_FETCH_COMPLETED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';

export const USER_ADD_STARTED = 'USER_ADD_STARTED';
export const USER_ADD_COMPLETED = 'USER_ADD_COMPLETED';
export const USER_ADD_FAILED = 'USER_ADD_FAILED';

export const USER_UPDATE_STARTED = 'USER_UPDATE_STARTED';
export const USER_UPDATE_COMPLETED = 'USER_UPDATE_COMPLETED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const USER_REMOVE_STARTED = 'USER_REMOVE_STARTED';
export const USER_REMOVE_COMPLETED = 'USER_REMOVE_COMPLETED';
export const USER_REMOVE_FAILED = 'USER_REMOVE_FAILED';
