export const MEDIATYPES_FETCH_STARTED = 'MEDIATYPES_FETCH_STARTED';
export const MEDIATYPES_FETCH_COMPLETED = 'MEDIATYPES_FETCH_COMPLETED';
export const MEDIATYPES_FETCH_FAILED = 'MEDIATYPES_FETCH_FAILED';